### ISSUE TITLE
large video file support

### ISSUE THREAD

**Issue by iNViTiON** [madebyhiro/codem-isoboxer#26]
I try this code with 3.5GB video file.
```
var ISOBoxer    = require('codem-isoboxer'),
    fs          = require('fs');
var arrayBuffer = new Uint8Array(fs.readFileSync('my_test_file.mp4')).buffer;
var parsedFile  = ISOBoxer.parseBuffer(arrayBuffer);
```
And I got this error.
```
class FastBuffer extends Uint8Array {}
^

RangeError: Invalid typed array length
```
The error happen with the third line `fs.readFileSync('my_test_file.mp4')` since it not support [large buffer](https://github.com/nodejs/node/issues/6560). I try to read only part of file in the beginning of file and end of file but it can't parse the box I try to.

How can I get a box from this large video? A normal GoPro video was larger than this limit and cause this to happen. ([refer issue](https://github.com/iNViTiON/GoPro-Tagging/issues/1))

**Comment by tieleman** [comment]
Which version of Node are you using for this? Then I can try and reproduce the situation.

**Comment by tieleman** [comment]
There's also an issue here that Node has a maximum buffer size of `0x7fffffff` bytes, which is roughly 2GB. So both `fs.readFile` and `fs.readFileSync` won't be able to read the full size of the file in one pass.

**Comment by iNViTiON** [comment]
I use node 6.3.1. I notice that maximum buffer size limit but I don't know what I have to do. Can I read out a box without read the whole file? Read the whole file also cause a long time for large video file about 500 MB.

**Comment by tieleman** [comment]
`codem-isoboxer` does support partial files/buffers, as long as the start of the file is on a box start. However, the 3.5GB file that's linked in the other issue contains a single `mdat` box that's already bigger than 2GB, so that will not work, unless you would write your own logic to skip that.

Other than that, it would require adding a streaming parser to `codem-isoboxer`, or a parser that would work on top of a raw file descriptor with random access to the file (and not keep the contents in memory). Since `codem-isoboxer` is mostly a browser-oriented library from the start, not much time was put into this to add extra support for specific Node features, but I'm open to it as long as it's something that can be excluded from browser builds for size concerns.

**Comment by iNViTiON** [comment]
Thank you for the information. I will think about it.

**Comment by JuanIrache** [comment]
Hey @iNViTiON , did you find a solution for this? I'm using the module in the front-end but loading it with a require statement (+webpack). It crashes on large files, so I guess it's the same problem.

Thanks
